[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py load_katakana_words && gunicorn katakanagame.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
